import { DeepAlphaClient, DeepAlphaApiError } from "./client";

const TOKEN =
  "eyJhbGciOiJSUzI1NiIsImtpZCI6IjdmYzBiZDkwODExYjdiYjVkMTI2OWY5ZDU0NzhiZTBkIiwidHlwIjoiSldUIn0.eyJleHAiOjE3NzgyMzMwNzksImlhdCI6MTc3ODIyOTQ3OSwidG9rZW5fdHlwZSI6ImNsaWVudCIsImFwaV9hY2Nlc3MiOlsicXNjLWFwaSIsInF0cy1hcGkiLCJxcmEtYXBpIiwicWhhLWFwaSIsInFhcC1hcGkiXSwicGVybWlzc2lvbnMiOlsicXJhOmNhdGVnb3JpZXM6cmVhZCIsInFyYTpmdW5kOnJlYWQiLCJxcmE6cm9ibzpyZWFkIiwicXJhOnJpc2s6cmVhZCIsInFyYTphbmFseXplOnJlYWQiLCJxcmE6c3RhdGVfYWR2aXNvcjpyZWFkIiwicXJhOnN0YXRlX2NvbXBhbnk6cmVhZCIsInFyYTpzdGF0ZV91c2VyOnJlYWQiLCJxcmE6c3RhdGVfc2Vzc2lvbjpyZWFkIiwicXJhOnN0YXRlX3Nlc3Npb25fZGF0YTpyZWFkIiwicXJhOnN0YXRlX2Fkdmlzb3I6bGlzdCIsInFyYTpzdGF0ZV9jb21wYW55Omxpc3QiLCJxcmE6c3RhdGVfdXNlcjpsaXN0IiwicXJhOnN0YXRlX3Nlc3Npb246bGlzdCIsInFyYTpzdGF0ZV9zZXNzaW9uX2RhdGE6bGlzdCIsInFyYTpzdGF0ZV9hZHZpc29yOmNyZWF0ZSIsInFyYTpzdGF0ZV9jb21wYW55OmNyZWF0ZSIsInFyYTpzdGF0ZV91c2VyOmNyZWF0ZSIsInFyYTpzdGF0ZV9zZXNzaW9uOmNyZWF0ZSIsInFyYTpzdGF0ZV9zZXNzaW9uX2RhdGE6Y3JlYXRlIiwicXJhOnN0YXRlX2Fkdmlzb3I6dXBkYXRlIiwicXJhOnN0YXRlX2NvbXBhbnk6dXBkYXRlIiwicXJhOnN0YXRlX3VzZXI6dXBkYXRlIiwicXJhOnN0YXRlX3Nlc3Npb246dXBkYXRlIiwicXJhOnN0YXRlX3Nlc3Npb25fZGF0YTp1cGRhdGUiLCJxcmE6c3RhdGVfYWR2aXNvcjpkZWxldGUiLCJxcmE6c3RhdGVfY29tcGFueTpkZWxldGUiLCJxcmE6c3RhdGVfdXNlcjpkZWxldGUiLCJxcmE6c3RhdGVfc2Vzc2lvbjpkZWxldGUiLCJxcmE6c3RhdGVfc2Vzc2lvbl9kYXRhOmRlbGV0ZSIsInFyYTpzdGF0ZV9jb21wYW55OmFkbWluIiwicXJhOnN0YXRlX3VzZXI6YWRtaW4iLCJxcmE6c3RhdGVfc2Vzc2lvbjphZG1pbiIsInFyYTpzdGF0ZV9zZXNzaW9uX2RhdGE6YWRtaW4iLCJxcmE6c3RhdGVfYWR2aXNvcjphZG1pbiIsInFyYTpzdGF0ZV9zZXNzaW9uX2dvYWw6bGlzdCIsInFyYTpzdGF0ZV9zZXNzaW9uX2dvYWw6cmVhZCIsInFyYTpzdGF0ZV9zZXNzaW9uX2dvYWw6Y3JlYXRlIiwicXJhOnN0YXRlX3Nlc3Npb25fZ29hbDp1cGRhdGUiLCJxcmE6c3RhdGVfc2Vzc2lvbl9nb2FsOmRlbGV0ZSIsInFyYTpzdGF0ZV9zZXNzaW9uX2dvYWw6YWRtaW4iLCJxcmE6cWF1dDpkZWxldGUiLCJxcmE6bmFtZXNwYWNlOnJlYWQiLCJxcmE6bmFtZXNwYWNlOmxpc3QiLCJxcmE6bmFtZXNwYWNlOmNyZWF0ZSIsInFyYTpuYW1lc3BhY2U6dXBkYXRlIiwicXJhOm5hbWVzcGFjZTpkZWxldGUiLCJxcmE6c3RhdGVfcGRmX3JlcG9ydDpyZWFkIiwicXJhOnN0YXRlX3BkZl9yZXBvcnQ6Y3JlYXRlIiwicXJhOnN0YXRlX3BkZl9yZXBvcnQ6dXBkYXRlIiwicXJhOmdsb2JhbF9jYXRlZ29yeTpyZWFkIiwicXJhOmdsb2JhbF9jYXRlZ29yeTpsaXN0IiwicXJhOmdsb2JhbF9jYXRlZ29yeTpjcmVhdGUiLCJxcmE6Z2xvYmFsX2NhdGVnb3J5OnVwZGF0ZSIsInFyYTpnbG9iYWxfY2F0ZWdvcnk6ZGVsZXRlIiwicXJhOmNvbmZpZzptYW5hZ2UiLCJxcmE6Y29uZmlnOnJlYWQiLCJxcmE6cmlzazpjcmVhdGUiLCJxc2M6cXNjOnJlYWQiLCJxdHM6cXRzOnJlYWQiLCJxdHM6cXRzOmNyZWF0ZSIsInF0czpxdHM6dXBkYXRlIiwicWhhOnRyYXBldHM6cmVhZCIsInFoYTptb3JuaW5nc3Rhcl9raWlkOnJlYWQiLCJxaGE6Y29tcGFueV9sb29rdXA6cmVhZCIsInFoYTpjdXN0b21fa2lpZDpyZWFkIiwicWhhOmN1c3RvbV9raWlkOmxpc3QiLCJxaGE6Y3VzdG9tX2tpaWQ6Y3JlYXRlIiwicWhhOmN1c3RvbV9raWlkOmRlbGV0ZSIsInFoYTptb3JuaW5nc3Rhcl9raWlkOmNyZWF0ZSIsInFoYTp0ZW5hbnRfY3JlZGVudGlhbDpyZWFkIiwicWhhOnRlbmFudF9jcmVkZW50aWFsOm1hbmFnZSIsInFhcDpzdGF0ZV9hZHZpc29yOnJlYWQiLCJxYXA6c3RhdGVfY29tcGFueTpyZWFkIiwicWFwOnN0YXRlX3VzZXI6cmVhZCIsInFhcDpzdGF0ZV9zZXNzaW9uOnJlYWQiLCJxYXA6c3RhdGVfc2Vzc2lvbl9kYXRhOnJlYWQiLCJxYXA6c3RhdGVfYWR2aXNvcjpsaXN0IiwicWFwOnN0YXRlX2NvbXBhbnk6bGlzdCIsInFhcDpzdGF0ZV91c2VyOmxpc3QiLCJxYXA6c3RhdGVfc2Vzc2lvbjpsaXN0IiwicWFwOnN0YXRlX3Nlc3Npb25fZGF0YTpsaXN0IiwicWFwOnN0YXRlX2Fkdmlzb3I6Y3JlYXRlIiwicWFwOnN0YXRlX2NvbXBhbnk6Y3JlYXRlIiwicWFwOnN0YXRlX3VzZXI6Y3JlYXRlIiwicWFwOnN0YXRlX3Nlc3Npb246Y3JlYXRlIiwicWFwOnN0YXRlX3Nlc3Npb25fZGF0YTpjcmVhdGUiLCJxYXA6c3RhdGVfYWR2aXNvcjp1cGRhdGUiLCJxYXA6c3RhdGVfY29tcGFueTp1cGRhdGUiLCJxYXA6c3RhdGVfdXNlcjp1cGRhdGUiLCJxYXA6c3RhdGVfc2Vzc2lvbjp1cGRhdGUiLCJxYXA6c3RhdGVfc2Vzc2lvbl9kYXRhOnVwZGF0ZSIsInFhcDpzdGF0ZV9hZHZpc29yOmRlbGV0ZSIsInFhcDpzdGF0ZV9jb21wYW55OmRlbGV0ZSIsInFhcDpzdGF0ZV91c2VyOmRlbGV0ZSIsInFhcDpzdGF0ZV9zZXNzaW9uOmRlbGV0ZSIsInFhcDpzdGF0ZV9zZXNzaW9uX2RhdGE6ZGVsZXRlIiwicWFwOnN0YXRlX2NvbXBhbnk6YWRtaW4iLCJxYXA6c3RhdGVfdXNlcjphZG1pbiIsInFhcDpzdGF0ZV9zZXNzaW9uOmFkbWluIiwicWFwOnN0YXRlX3Nlc3Npb25fZGF0YTphZG1pbiIsInFhcDpzdGF0ZV9zZXNzaW9uX2dvYWw6bGlzdCIsInFhcDpzdGF0ZV9zZXNzaW9uX2dvYWw6cmVhZCIsInFhcDpzdGF0ZV9zZXNzaW9uX2dvYWw6Y3JlYXRlIiwicWFwOnN0YXRlX3Nlc3Npb25fZ29hbDp1cGRhdGUiLCJxYXA6c3RhdGVfc2Vzc2lvbl9nb2FsOmRlbGV0ZSIsInFhcDpzdGF0ZV9zZXNzaW9uX2dvYWw6YWRtaW4iLCJxYXA6c3RhdGVfaW52ZXN0b3I6bGlzdCIsInFhcDpzdGF0ZV9pbnZlc3RvcjpyZWFkIiwicWFwOnN0YXRlX2ludmVzdG9yOmNyZWF0ZSIsInFhcDpzdGF0ZV9pbnZlc3Rvcjp1cGRhdGUiLCJxYXA6c3RhdGVfaW52ZXN0b3I6ZGVsZXRlIiwicWFwOnN0YXRlX2ludmVzdG9yOmFkbWluIiwicWFwOnN0YXRlX3BkZl9yZXBvcnQ6cmVhZCIsInFhcDpzdGF0ZV9wZGZfcmVwb3J0OmNyZWF0ZSIsInFhcDpzdGF0ZV9wZGZfcmVwb3J0OnVwZGF0ZSIsInFhcDpzdGF0ZV9hY2NvdW50OnJlYWQiLCJxYXA6c3RhdGVfYWNjb3VudDpsaXN0IiwicWFwOnN0YXRlX2FjY291bnQ6Y3JlYXRlIiwicWFwOnN0YXRlX2FjY291bnQ6dXBkYXRlIiwicWFwOnN0YXRlX2FjY291bnQ6ZGVsZXRlIiwicWFwOnNlc3Npb246YWRtaW4iLCJxYXA6cGRmX2RvY3VtZW50OmNyZWF0ZSIsInFhcDpyZXBvcnRfdGVtcGxhdGU6YWRtaW4iLCJxYXA6cmVwb3J0X3RlbXBsYXRlOmxpc3QiLCJxYXA6cmVwb3J0X2F0dGFjaG1lbnQ6bGlzdCIsInFhcDpyZXBvcnRfYXR0YWNobWVudDphZG1pbiJdLCJwZXJtaXNzaW9uX2NvbnRleHQiOnt9LCJ1c2VyX25hbWUiOiJxZi1lbXBsb3llZS1iam9ybmFyIiwidXNlcl9pZCI6MzQsImNsaWVudF9pZCI6IjcyYTA5YjhlLWNkZTUtNDdkZi1iNTBmLWU4ZjIyYzdmMjk4OSIsInJvbGVzIjpbImFkdmlzb3JfYWRtaW4iXSwiaXNzIjoiaHR0cHM6Ly9xYXV0aC1hcGkudGVzdC5kZWVwYWxwaGEuZGV2L2FwaS92MiIsInRlbmFudF91cmwiOiJodHRwczovL3Rlc3QuZGVlcGFscGhhLmRldiJ9.Dj6KbPeZjRfeODyDHFMO9tuy9JVm1pYmlUVaRAaNw9u36qHrahq6M8ukkJUW_HbWIknuC_t8rOM202JXXOQ72TX1CrwqQ0LqIW-xx6pmMZFZxhQ9mksaVwyoJwLWW3FdQVMXQeqM0yTjMcd3hxjbO7xPr1zOAyflrqrVA72mIqsmK9XDX8xMeMEtOE4G5xIAt0si5x08OqrbvKC7m4ZWr5p-FLnmRot_w-DfyZuCituJOXyS1pmkuz8luI3ScChLW0gGgqIZRvSGCbCCHsEZNBtE_SRL6eeCWanxHb7n61zZJaXgPPcfje5V4cZ6dVAUnDLmJBS4eHx3OKQEEgQYWg";

const client = new DeepAlphaClient({ accessToken: TOKEN });

async function run() {
  console.log("→ Step 1: listAdvisors");
  const advisorsRes = (await client.listAdvisors()) as any;
  const advisorId: string = advisorsRes.advisors[0].advisor_id;
  console.log(`  picked advisor_id=${advisorId} (${advisorsRes.advisors[0].name})`);

  console.log("\n→ Step 2: listInvestors");
  let investorId: string | undefined;
  const investorsRes = (await client.listInvestors({ page: 1, pageSize: 5 })) as any;
  const existingInvestors =
    investorsRes?.investors ?? investorsRes?.data ?? investorsRes?.items ?? [];
  console.log(`  found ${existingInvestors.length} existing investor(s)`);

  if (existingInvestors.length > 0) {
    investorId = existingInvestors[0].investor_id ?? existingInvestors[0].id;
    console.log(`  using existing investor_id=${investorId}`);
  } else {
    console.log("  creating a fresh investor for the test");
    const created = (await client.createInvestor({
      name: "Smoke Test Investor " + Date.now(),
      advisor_id: advisorId,
    } as any)) as any;
    console.log("  createInvestor response:", JSON.stringify(created, null, 2));
    investorId = created?.investor_id ?? created?.id ?? created?.investor?.investor_id;
  }

  if (!investorId) throw new Error("could not obtain an investor_id");

  console.log(
    `\n→ Step 3: createStateSession (advisor_id=${advisorId}, investor_id=${investorId})`,
  );
  const session = await client.createStateSession({
    advisor_id: advisorId,
    investor_id: investorId,
    name: "Smoke test session " + new Date().toISOString(),
    advice_type: "MiFIID II investment Advice",
  } as any);
  console.log("createStateSession response:");
  console.log(JSON.stringify(session, null, 2));
}

function formatErr(e: unknown) {
  if (e instanceof DeepAlphaApiError) {
    return JSON.stringify({ status: e.status, message: e.message, body: e.body }, null, 2);
  }
  return e instanceof Error ? `${e.name}: ${e.message}` : String(e);
}

run();
